# Generated by Django 2.1.7 on 2019-04-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190428_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='id',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='disciplina',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
