/* MSSQL - DQL - DATA QUERY LANGUAGE */

/* 

SELECT - LISTA DE SELEÇÃO - 5
FROM - TABELA DE ORIGEM - 1
WHERE - CONDIÇÃO DE PESQUISA - 2
GROUP BY - AGRUPAR A SELEÇÃO - 3
HAVING - CONDIÇÃO DE AGRUPAMENTO - 4
ORDER BY - ORDEM DA LISTA - 6

*/
